import { Injectable } from '@angular/core';
import { ResidentModel } from './resident-model';
import { BehaviorSubject } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class ResidentServices {

  private residentsSubject = new BehaviorSubject<ResidentModel[]>([
    {
      id: 'RES-1001',
      firstName: 'Fares',
      lastName: 'Rahmani',
      email: 'fares.rahmani@example.com',
      phone: '123-456-7890',
      address: '123 Main St',
      status: 'Active',
      House: 'Block A,Unit 101',
      block: 'Block A',
      birthDate: '2023-01-01',
      createdAt: '2023-01-01',
    },
    {
      id: 'RES-1002',
      firstName: 'Hassan',
      lastName: 'Rahmani',
      email: 'hassan.rahmani@example.com',
      phone: '098-765-4321',
      address: '456 Elm St',
      status: 'Inactive',
      House: 'Block B, Unit 202',
      block: 'Block B',
      birthDate: '2023-01-01',
      createdAt: '2023-01-01',
    },
    {
      id: 'RES-1003',
      firstName: 'Omar',
      lastName: 'Rahmani',
      email: 'omar.rahmani@example.com',
      phone: '123-456-7890',
      address: '123 Main St',
      status: 'Active',
      House: 'Block A, Unit 101',
      block: 'Block A',
      birthDate: '2023-01-01',
      createdAt: '2023-01-01',
    },
    {
      id: 'RES-1004',
      firstName: 'Omar',
      lastName: 'Rahmani',
      email: 'omar.rahmani@example.com',
      phone: '123-456-7890',
      address: '123 Main St',
      status: 'Active',
      House: 'Block A, Unit 101',
      block: 'Block A',
      birthDate: '2023-01-01',
      createdAt: '2023-01-01',
    },
    {
      id: 'RES-1005',
      firstName: 'Ahmed',
      lastName: 'Rahmani',
      email: 'ahmed.rahmani@example.com',
      phone: '123-456-7890',
      address: '123 Main St',
      status: 'Active',
      House: 'Block A, Unit 101',
      block: 'Block A',
      birthDate: '2023-01-01',
      createdAt: '2023-01-01',
    },
    {
      id: 'RES-1006',
      firstName: 'sabeh',
      lastName: 'Rahmani',
      email: 'sabeh.rahmani@example.com',
      phone: '123-456-7890',
      address: '123 Main St',
      status: 'Active',
      House: 'Block A, Unit 101',
      block: 'Block A',
      birthDate: '2023-01-01',
      createdAt: '2023-01-01',
    },
    {
      id: 'RES-1007',
      firstName: 'sara',
      lastName: 'Rahmani',
      email: 'sara.rahmani@example.com',
      phone: '123-456-7890',
      address: '123 Main St',
      status: 'Active',
      House: 'Block A, Unit 101',
      block: 'Block A',
      birthDate: '2023-01-01',
      createdAt: '2023-01-01',
    },
    {
      id: 'RES-1008',
      firstName: 'sara',
      lastName: 'Rahmani',
      email: 'sara.rahmani@example.com',
      phone: '123-456-7890',
      address: '123 Main St',
      status: 'Active',
      House: 'Block A, Unit 101',
      block: 'Block A',
      birthDate: '2023-01-01',
      createdAt: '2023-01-01',
    },
    {
      id: 'RES-1009',
      firstName: 'ter',
      lastName: 'Rahmani',
      email: 'ter.rahmani@example.com',
      phone: '123-456-7890',
      address: '123 Main St',
      status: 'Active',
      House: 'Block A, Unit 101',
      block: 'Block A',
      birthDate: '2023-01-01',
      createdAt: '2023-01-01',
    },
    {
      id: 'RES-1010',
      firstName: 'ter',
      lastName: 'Rahmani',
      email: 'ter.rahmani@example.com',
      phone: '123-456-7890',
      address: '123 Main St',
      status: 'Active',
      House: 'Block A, Unit 101',
      block: 'Block A',
      birthDate: '2023-01-01',
      createdAt: '2023-01-01',
    },
    {
      id: 'RES-1011',
      firstName: 'ter',
      lastName: 'Rahmani',
      email: 'ter.rahmani@example.com',
      phone: '123-456-7890',
      address: '123 Main St',
      status: 'Active',
      House: 'Block A, Unit 101',
      block: 'Block A',
      birthDate: '2023-01-01',
      createdAt: '2023-01-01',
    },
    {
      id: 'RES-1012',
      firstName: 'ter',
      lastName: 'Rahmani',
      email: 'ter.rahmani@example.com',
      phone: '123-456-7890',
      address: '123 Main St',
      status: 'Active',
      House: 'Block A, Unit 101',
      block: 'Block A',
      birthDate: '2023-01-01',
      createdAt: '2023-01-01',
    },
    {
      id: 'RES-1013',
      firstName: 'ter',
      lastName: 'Rahmani',
      email: 'ter.rahmani@example.com',
      phone: '123-456-7890',
      address: '123 Main St',
      status: 'Active',
      House: 'Block A, Unit 101',
      block: 'Block A',
      birthDate: '2023-01-01',
      createdAt: '2023-01-01',
    },
    {
      id: 'RES-1014',
      firstName: 'ter',
      lastName: 'Rahmani',
      email: 'ter.rahmani@example.com',
      phone: '123-456-7890',
      address: '123 Main St',
      status: 'Active',
      House: 'Block A, Unit 101',
      block: 'Block A',
      birthDate: '2023-01-01',
      createdAt: '2023-01-01',
    },
    {
      id: 'RES-1015',
      firstName: 'ter',
      lastName: 'Rahmani',
      email: 'ter.rahmani@example.com',
      phone: '123-456-7890',
      address: '123 Main St',
      status: 'Active',
      House: 'Block A, Unit 101',
      block: 'Block A',
      birthDate: '2023-01-01',
      createdAt: '2023-01-01',
    },
    {
      id: 'RES-1016',
      firstName: 'ter',
      lastName: 'Rahmani',
      email: 'ter.rahmani@example.com',
      phone: '123-456-7890',
      address: '123 Main St',
      status: 'Active',
      House: 'Block A, Unit 101',
      block: 'Block A',
      birthDate: '2023-01-01',
      createdAt: '2023-01-01',
    },
    {
      id: 'RES-1017',
      firstName: 'ter',
      lastName: 'Rahmani',
      email: 'ter.rahmani@example.com',
      phone: '123-456-7890',
      address: '123 Main St',
      status: 'Active',
      House: 'Block A, Unit 101',
      block: 'Block A',
      birthDate: '2023-01-01',
      createdAt: '2023-01-01',
    },
    {
      id: 'RES-1018',
      firstName: 'ter',
      lastName: 'Rahmani',
      email: 'ter.rahmani@example.com',
      phone: '123-456-7890',
      address: '123 Main St',
      status: 'Active',
      House: 'Block A, Unit 101',
      block: 'Block A',
      birthDate: '2023-01-01',
      createdAt: '2023-01-01',
    },
    {
      id: 'RES-1019',
      firstName: 'ter',
      lastName: 'Rahmani',
      email: 'ter.rahmani@example.com',
      phone: '123-456-7890',
      address: '123 Main St',
      status: 'Active',
      House: 'Block A, Unit 101',
      block: 'Block A',
      birthDate: '2023-01-01',
      createdAt: '2023-01-01',
    },
    {
      id: 'RES-1020',
      firstName: 'ter',
      lastName: 'Rahmani',
      email: 'ter.rahmani@example.com',
      phone: '123-456-7890',
      address: '123 Main St',
      status: 'Active',
      House: 'Block A, Unit 101',
      block: 'Block A',
      birthDate: '2023-01-01',
      createdAt: '2023-01-01',
    },
    {
      id: 'RES-1021',
      firstName: 'ter',
      lastName: 'Rahmani',
      email: 'ter.rahmani@example.com',
      phone: '123-456-7890',
      address: '123 Main St',
      status: 'Active',
      House: 'Block A, Unit 101',
      block: 'Block A',
      birthDate: '2023-01-01',
      createdAt: '2023-01-01',
    },
    {
      id: 'RES-1022',
      firstName: 'ter',
      lastName: 'Rahmani',
      email: 'ter.rahmani@example.com',
      phone: '123-456-7890',
      address: '123 Main St',
      status: 'Active',
      House: 'Block A, Unit 101',
      block: 'Block A',
      birthDate: '2023-01-01',
      createdAt: '2023-01-01',
    },
    {
      id: 'RES-1023',
      firstName: 'ter',
      lastName: 'Rahmani',
      email: 'ter.rahmani@example.com',
      phone: '123-456-7890',
      address: '123 Main St',
      status: 'Active',
      House: 'Block A, Unit 101',
      block: 'Block A',
      birthDate: '2023-01-01',
      createdAt: '2023-01-01',
    },
    {
      id: 'RES-1024',
      firstName: 'ter',
      lastName: 'Rahmani',
      email: 'ter.rahmani@example.com',
      phone: '123-456-7890',
      address: '123 Main St',
      status: 'Active',
      House: 'Block A, Unit 101',
      block: 'Block A',
      birthDate: '2023-01-01',
      createdAt: '2023-01-01',
    },
    {
      id: 'RES-1025',
      firstName: 'ter',
      lastName: 'Rahmani',
      email: 'ter.rahmani@example.com',
      phone: '123-456-7890',
      address: '123 Main St',
      status: 'Active',
      House: 'Block A, Unit 101',
      block: 'Block A',
      birthDate: '2023-01-01',
      createdAt: '2023-01-01',
    }
  ]);

  residents$ = this.residentsSubject.asObservable();

  addResident(resident: Omit<ResidentModel, 'id' | 'createdAt' | 'status' | 'block'>) {
    const currentResidents = this.residentsSubject.value;
    const lastId = currentResidents.length > 0
      ? parseInt(currentResidents[currentResidents.length - 1].id.split('-')[1])
      : 1000;

    const newResident: ResidentModel = {
      ...resident,
      id: `RES-${lastId + 1}`,
      status: 'Active',
      createdAt: new Date().toISOString().split('T')[0],
      block: resident.House ? resident.House.split(',')[0] : '', // Extract block from House if possible
      address: resident.address,
      birthDate: resident.birthDate
    };

    this.residentsSubject.next([...currentResidents, newResident]);
  }

  getResidentById(id: string): ResidentModel | undefined {
    return this.residentsSubject.value.find(r => r.id === id);
  }

  updateResident(updatedResident: ResidentModel) {
    const currentResidents = this.residentsSubject.value;
    const index = currentResidents.findIndex(r => r.id === updatedResident.id);
    if (index !== -1) {
      currentResidents[index] = updatedResident;
      this.residentsSubject.next([...currentResidents]);
    }
  }
}
